In [1]:
#dot product----
import numpy as np
#first matrix values
print("enter size of first matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
#second matrix values
B=[]
print("enter size of second matrix")
a=int(input())
b=int(input())
print("Enter the elements")
for i in range(a):
    row=[]
    for j in range(b):
        row.append(int(input()))
    B.append(row) 
print("The first matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
print("The sercond matrix is")
for i in range(a):
    for j in range(b):
        print(B[i][j],end=" ")
    print()
res= np.dot(A,B)
print("Dot product \n",res)


enter size of first matrix


 2
 2


Enter the elements


 1
 2
 3
 4


enter size of second matrix


 2
 2


Enter the elements


 2
 3
 4
 5


The first matrix is
1 2 
3 4 
The sercond matrix is
2 3 
4 5 
Dot product 
 [[10 13]
 [22 29]]


In [2]:
#transpose---------
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
res=np.transpose(A)
print("The transpose is \n",res)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The transpose is 
 [[1 3]
 [2 4]]


In [3]:
#trace----
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
res=np.trace(A)
print("The trace is \n",res)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The trace is 
 5


In [4]:
#rank---------
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
res=np.linalg.matrix_rank(A)
print("The rank is \n",res)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The rank is 
 2


In [5]:
#determinant
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
res=np.linalg.det(A)
print("The determinant is \n",res)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The determinant is 
 -2.0000000000000004


In [6]:
#inverse----------
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
res=np.linalg.inv(A)
print("The inverse is \n",res)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The inverse is 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
#eigen values and eigen vectors
import numpy as np
# matrix values
print("enter size of matrix")
A=[]
x=int(input())
y=int(input())
print("Enter the elements")
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    A.append(row) 
print("The matrix is")
for i in range(x):
    for j in range(y):
        print(A[i][j],end=" ")
    print()
w,v=np.linalg.eig(A)
print("The eigen value is \n",w)
print("The eigen vector is \n",v)

enter size of matrix


 2
 2


Enter the elements


 1
 2
 3
 4


The matrix is
1 2 
3 4 
The eigen value is 
 [-0.37228132  5.37228132]
The eigen vector is 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
